## Smartphone_Addiction - Exploratory Data Analysis            
*** (Age Range - 12-70 years) - 3000 Survey Participants ***

In [14]:
import pandas as pd 
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np  

pd.set_option('display.max_columns', 50)        # View all the columns without getting truncated

In [27]:
# Loading second dataset - CSV format

data = pd.read_csv("../data/global_smartphone_addiction.csv")
df = pd.DataFrame(data)

#### Step 1: Understanding the dataset

1. First 10 lines of dataframe 
2. Dataframe Info 
3. check for null or duplicate values
4. Describe function to see the stats
5. Categorical Breakdown
6. Filtered views

In [16]:
# First 10 lines of dataframe
df.head(10)

,User_ID,Country,Age,Gender,Occupation,Education_Level,Income_USD,Daily_Screen_Time_Hours,Phone_Unlocks_Per_Day,Social_Media_Usage_Hours,Gaming_Usage_Hours,Streaming_Usage_Hours,Messaging_Usage_Hours,Work_Related_Usage_Hours,Sleep_Hours,Physical_Activity_Hours,Mental_Health_Score,Depression_Score,Anxiety_Score,Stress_Level,Relationship_Status,Has_Children,Urban_or_Rural,Time_Spent_With_Family_Hours,Online_Shopping_Hours,Internet_Connection_Type,Primary_Device_Brand,Has_Screen_Time_Management_App,Self_Reported_Addiction_Level,Monthly_Data_Usage_GB,Has_Night_Mode_On,Age_First_Phone,Push_Notifications_Per_Day,Tech_Savviness_Score
0,1,India,32,Male,Salesperson,High School,43865.49,5.81,75,0.84,-1.55,3.36,1.44,2.14,5.22,1.32,61.47,80.80,23.72,95.80,Single,No,Rural,1.70,1.85,5G,Other,No,Low,16.43,Yes,16,106,39.36
1,2,UK,26,Male,Artist,Master's,41868.19,9.05,61,3.13,2.50,0.80,2.42,1.44,6.23,0.66,96.11,98.99,39.72,25.03,In Relationship,No,Rural,0.90,0.66,4G,Samsung,Yes,Severe,32.87,No,12,111,9.45
2,3,Germany,70,Other,Doctor,High School,59636.51,5.76,58,2.12,1.96,1.84,1.98,1.92,6.57,1.93,73.68,44.64,94.47,99.54,Single,Yes,Urban,1.69,-0.14,WiFi,Samsung,Yes,Severe,27.45,No,18,90,50.27
3,4,UK,44,Female,Engineer,NaN,39022.07,6.71,80,1.60,2.70,1.90,2.43,1.82,7.27,0.94,53.42,10.89,5.03,66.49,In Relationship,No,Urban,1.11,0.17,3G,Apple,Yes,Moderate,30.85,No,17,60,30.82
4,5,Brazil,46,Other,Student,NaN,-783.98,6.31,136,1.51,1.73,1.48,1.30,1.76,5.43,1.04,67.01,37.54,17.29,14.72,Divorced,No,Urban,1.06,0.58,3G,Xiaomi,No,High,10.38,Yes,18,127,21.70
5,6,Japan,34,Male,Student,PhD,19751.80,8.94,129,2.28,2.49,0.97,1.39,2.66,6.21,1.14,25.15,97.45,65.54,63.04,Married,No,Rural,1.32,0.40,5G,Xiaomi,No,Low,17.51,No,8,78,14.38
6,7,China,51,Male,Doctor,Master's,22956.76,4.18,65,1.75,2.07,0.33,1.58,1.98,4.84,1.33,4.94,27.16,80.16,83.20,In Relationship,No,Urban,1.08,0.88,WiFi,Huawei,Yes,Severe,44.52,No,11,82,79.63
7,8,Russia,68,Male,Salesperson,High School,62102.93,10.05,87,2.13,2.99,1.67,2.06,1.51,6.81,1.43,44.33,95.16,20.94,62.53,Divorced,Yes,Rural,1.02,0.77,5G,Samsung,Yes,Low,26.66,No,12,102,52.16
8,9,Nigeria,33,Other,Salesperson,NaN,26629.11,7.45,50,2.02,0.49,2.41,1.60,2.98,6.54,1.40,55.45,59.96,95.10,95.94,Divorced,No,Urban,0.77,0.10,5G,Apple,Yes,High,24.49,No,8,85,31.52
9,10,India,38,Other,Salesperson,High School,43121.39,6.87,95,2.27,0.00,2.44,1.37,2.55,6.04,1.55,85.13,38.30,4.32,33.65,Divorced,No,Urban,1.74,1.82,4G,OnePlus,Yes,High,29.05,No,14,120,97.40

In [17]:
# To view the summary of the dataframe
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 34 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   User_ID                         3000 non-null   int64
 1   Country                         3000 non-null   str
 2   Age                             3000 non-null   int64
 3   Gender                          3000 non-null   str
 4   Occupation                      3000 non-null   str
 5   Education_Level                 2388 non-null   str
 6   Income_USD                      3000 non-null   float64
 7   Daily_Screen_Time_Hours         3000 non-null   float64
 8   Phone_Unlocks_Per_Day           3000 non-null   int64
 9   Social_Media_Usage_Hours        3000 non-null   float64
 10  Gaming_Usage_Hours              3000 non-null   float64
 11  Streaming_Usage_Hours           3000 non-null   float64
 12  Messaging_Usage_Hours           3000 non-null   float64
 13  Work_Related_Usage_Hours        3000 non-null   float64
 14  Sleep_Hours                     3000 non-null   float64
 15  Physical_Activity_Hours         3000 non-null   float64
 16  Mental_Health_Score             3000 non-null   float64
 17  Depression_Score                3000 non-null   float64
 18  Anxiety_Score                   3000 non-null   float64
 19  Stress_Level                    3000 non-null   float64
 20  Relationship_Status             3000 non-null   str
 21  Has_Children                    3000 non-null   str
 22  Urban_or_Rural                  3000 non-null   str
 23  Time_Spent_With_Family_Hours    3000 non-null   float64
 24  Online_Shopping_Hours           3000 non-null   float64
 25  Internet_Connection_Type        3000 non-null   str
 26  Primary_Device_Brand            3000 non-null   str
 27  Has_Screen_Time_Management_App  3000 non-null   str
 28  Self_Reported_Addiction_Level   3000 non-null   str
 29  Monthly_Data_Usage_GB           3000 non-null   float64
 30  Has_Night_Mode_On               3000 non-null   str
 31  Age_First_Phone                 3000 non-null   int64
 32  Push_Notifications_Per_Day      3000 non-null   int64
 33  Tech_Savviness_Score            3000 non-null   float64
dtypes: float64(17), int64(5), str(12)
memory usage: 797.0 KB

In [18]:
# checking for null values
df.isnull().sum()

User_ID                             0
Country                             0
Age                                 0
Gender                              0
Occupation                          0
Education_Level                   612
Income_USD                          0
Daily_Screen_Time_Hours             0
Phone_Unlocks_Per_Day               0
Social_Media_Usage_Hours            0
Gaming_Usage_Hours                  0
Streaming_Usage_Hours               0
Messaging_Usage_Hours               0
Work_Related_Usage_Hours            0
Sleep_Hours                         0
Physical_Activity_Hours             0
Mental_Health_Score                 0
Depression_Score                    0
Anxiety_Score                       0
Stress_Level                        0
Relationship_Status                 0
Has_Children                        0
Urban_or_Rural                      0
Time_Spent_With_Family_Hours        0
Online_Shopping_Hours               0
Internet_Connection_Type            0
Primary_Device_Brand                0
Has_Screen_Time_Management_App      0
Self_Reported_Addiction_Level       0
Monthly_Data_Usage_GB               0
Has_Night_Mode_On                   0
Age_First_Phone                     0
Push_Notifications_Per_Day          0
Tech_Savviness_Score                0
dtype: int64

In [19]:
# Checking for duplicates
print(df.duplicated().sum())

0

In [20]:
# To view descriptive statistics

df.describe()

,User_ID,Age,Income_USD,Daily_Screen_Time_Hours,Phone_Unlocks_Per_Day,Social_Media_Usage_Hours,Gaming_Usage_Hours,Streaming_Usage_Hours,Messaging_Usage_Hours,Work_Related_Usage_Hours,Sleep_Hours,Physical_Activity_Hours,Mental_Health_Score,Depression_Score,Anxiety_Score,Stress_Level,Time_Spent_With_Family_Hours,Online_Shopping_Hours,Monthly_Data_Usage_GB,Age_First_Phone,Push_Notifications_Per_Day,Tech_Savviness_Score
count,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000,3000.00000,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000
mean,1500.500000,41.307333,29779.511047,5.984397,79.699667,1.988487,1.486617,1.981433,1.48917,1.995423,6.492713,0.996127,50.045053,50.343517,49.918940,49.383413,1.451450,0.789503,24.871843,13.954000,99.053667,49.457427
std,866.169729,17.052345,15377.473743,2.018142,25.155683,0.983224,0.997255,1.004578,0.50883,0.972245,0.993489,0.499560,28.738761,29.003991,29.041927,28.588983,0.803806,0.505463,9.791275,3.736202,30.330163,28.842681
min,1.000000,12.000000,-25622.660000,-0.500000,-7.000000,-1.810000,-1.930000,-1.910000,-0.18000,-1.160000,2.810000,-0.840000,0.000000,0.040000,0.010000,0.040000,-1.610000,-0.880000,-10.960000,8.000000,-21.000000,0.010000
25%,750.750000,27.000000,19482.705000,4.597500,63.000000,1.340000,0.810000,1.290000,1.14000,1.340000,5.840000,0.650000,25.317500,25.665000,24.670000,24.260000,0.920000,0.460000,18.302500,11.000000,79.000000,23.665000
50%,1500.500000,42.000000,30002.710000,5.980000,80.000000,2.010000,1.510000,2.010000,1.50000,1.980000,6.480000,1.010000,50.630000,50.155000,50.125000,48.800000,1.450000,0.780000,25.045000,14.000000,99.000000,49.150000
75%,2250.250000,56.000000,40352.017500,7.302500,96.000000,2.640000,2.180000,2.650000,1.84000,2.670000,7.160000,1.330000,75.120000,75.420000,75.400000,74.422500,1.990000,1.130000,31.462500,17.000000,119.000000,74.137500
max,3000.000000,70.000000,79829.550000,12.870000,182.000000,5.050000,4.860000,5.180000,3.07000,5.260000,10.320000,2.800000,99.970000,99.830000,100.000000,99.880000,4.520000,2.600000,54.850000,20.000000,204.000000,99.940000

In [21]:
# Categorical Breakdown - By Gender
df['Gender'].value_counts()

Gender
Male      1047
Other      990
Female     963
Name: count, dtype: int64

In [26]:
df['Age'].value_counts().sort_index()

Age
12    43
13    59
14    61
15    37
16    53
17    50
18    49
19    51
20    43
21    51
22    42
23    50
24    36
25    48
26    53
27    48
28    67
29    59
30    47
31    39
32    60
33    63
34    41
35    57
36    58
37    58
38    41
39    45
40    47
41    39
42    57
43    55
44    54
45    49
46    50
47    62
48    49
49    56
50    58
51    43
52    39
53    47
54    41
55    55
56    48
57    45
58    50
59    55
60    59
61    54
62    61
63    51
64    47
65    56
66    51
67    57
68    57
69    49
70    50
Name: count, dtype: int64

**Note**

This dataset was fairly clean to begin with. Gender and age distributions appear balanced — this leads to believe the dataset may be synthetic, since real-world data is rarely this evenly distributed.

In [23]:
# filter with .loc function
df.loc[df["Daily_Screen_Time_Hours"] > 5].sort_values("Age", ascending=True)

,User_ID,Country,Age,Gender,Occupation,Education_Level,Income_USD,Daily_Screen_Time_Hours,Phone_Unlocks_Per_Day,Social_Media_Usage_Hours,Gaming_Usage_Hours,Streaming_Usage_Hours,Messaging_Usage_Hours,Work_Related_Usage_Hours,Sleep_Hours,Physical_Activity_Hours,Mental_Health_Score,Depression_Score,Anxiety_Score,Stress_Level,Relationship_Status,Has_Children,Urban_or_Rural,Time_Spent_With_Family_Hours,Online_Shopping_Hours,Internet_Connection_Type,Primary_Device_Brand,Has_Screen_Time_Management_App,Self_Reported_Addiction_Level,Monthly_Data_Usage_GB,Has_Night_Mode_On,Age_First_Phone,Push_Notifications_Per_Day,Tech_Savviness_Score
1932,1933,Japan,12,Male,Student,High School,53068.74,7.90,106,0.71,0.78,3.43,1.21,4.12,6.39,0.42,23.51,83.46,52.86,4.49,In Relationship,No,Urban,2.73,0.67,3G,OnePlus,Yes,Low,14.59,Yes,13,154,7.29
2012,2013,Brazil,12,Female,Unemployed,NaN,43883.36,7.52,30,2.37,2.12,2.79,1.26,2.98,5.60,1.42,82.96,35.51,51.32,33.36,In Relationship,Yes,Rural,0.48,0.79,WiFi,OnePlus,Yes,High,20.14,Yes,14,108,46.14
1958,1959,USA,12,Female,Student,NaN,17566.36,7.91,81,-0.26,1.61,2.57,1.63,1.83,9.13,0.79,72.69,38.23,21.40,93.39,Divorced,Yes,Urban,2.65,1.25,WiFi,Xiaomi,Yes,Low,25.81,No,11,153,27.12
2731,2732,Japan,12,Male,Teacher,Bachelor's,15327.88,5.95,74,2.86,1.20,1.47,0.27,2.73,6.32,1.95,6.25,57.13,58.86,39.62,Divorced,No,Rural,2.61,0.31,5G,Huawei,Yes,Moderate,22.96,No,16,74,62.26
84,85,Mexico,12,Female,Teacher,NaN,23264.34,9.80,88,2.53,1.30,3.14,1.82,2.49,6.05,0.39,0.28,58.83,12.46,94.93,Divorced,Yes,Urban,1.68,0.22,5G,Samsung,No,Moderate,23.17,No,19,121,77.98
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1846,1847,China,70,Male,Manager,High School,38826.22,7.99,70,2.64,0.63,3.95,2.03,1.89,6.07,1.41,79.15,94.19,79.41,81.79,Divorced,Yes,Rural,0.63,1.03,3G,OnePlus,Yes,Severe,30.05,No,10,90,67.20
2002,2003,USA,70,Female,Unemployed,NaN,27844.91,6.65,67,1.92,0.91,-0.23,1.92,1.78,5.72,-0.18,82.27,86.65,65.31,6.97,Divorced,No,Urban,1.88,0.47,5G,OnePlus,No,Severe,24.07,No,20,61,81.06
2974,2975,Brazil,70,Male,Salesperson,Bachelor's,36069.44,7.75,104,1.89,1.47,3.59,1.63,2.03,5.05,0.27,32.44,28.11,89.32,66.18,Married,Yes,Rural,-0.23,0.77,4G,Other,No,Moderate,21.84,No,13,116,55.65
2,3,Germany,70,Other,Doctor,High School,59636.51,5.76,58,2.12,1.96,1.84,1.98,1.92,6.57,1.93,73.68,44.64,94.47,99.54,Single,Yes,Urban,1.69,-0.14,WiFi,Samsung,Yes,Severe,27.45,No,18,90,50.27
2989,2990,Russia,70,Female,Unemployed,Bachelor's,36481.02,7.07,59,1.11,1.69,1.81,1.38,3.11,6.04,0.97,2.04,7.89,81.52,40.70,Single,No,Urban,0.70,1.36,4G,Other,Yes,Moderate,22.94,Yes,8,68,87.30

#### Step 2: Data Preparation

1. Checking and removing duplicate rows (By calling the function)
2. Renaming column names to match teen_screentime_addiction

In [28]:
# checking for duplicates using functions.py
import sys
sys.path.append("..")

from functions import check_duplicates
global_df = check_duplicates(df, name="global_smartphone_addiction.csv")

global_smartphone_addiction.csv has duplicate rows: 0

In [ ]:
# To view column names
df.columns

Index(['User_ID', 'Country', 'Age', 'Gender', 'Occupation', 'Education_Level',
       'Income_USD', 'Daily_Screen_Time_Hours', 'Phone_Unlocks_Per_Day',
       'Social_Media_Usage_Hours', 'Gaming_Usage_Hours',
       'Streaming_Usage_Hours', 'Messaging_Usage_Hours',
       'Work_Related_Usage_Hours', 'Sleep_Hours', 'Physical_Activity_Hours',
       'Mental_Health_Score', 'Depression_Score', 'Anxiety_Score',
       'Stress_Level', 'Relationship_Status', 'Has_Children', 'Urban_or_Rural',
       'Time_Spent_With_Family_Hours', 'Online_Shopping_Hours',
       'Internet_Connection_Type', 'Primary_Device_Brand',
       'Has_Screen_Time_Management_App', 'Self_Reported_Addiction_Level',
       'Monthly_Data_Usage_GB', 'Has_Night_Mode_On', 'Age_First_Phone',
       'Push_Notifications_Per_Day', 'Tech_Savviness_Score'],
      dtype='str')

In [ ]:
# Rename the columns to match with teen_screentime_addiction.ipynb